Repository FabianAronsson/Concrete-Indium, pull requests merged in 2020-11, with the labels that each got.

#2 ✨[WIP]Modified tsconfig
  src/backend/tsconfig.json
Labels: enhancement

#8 Jw create basic wireframe for live chat
  res/design/Wireframes.txt
Labels: enhancement

#11 📝Finished the contribution guide and third party documentaion links...
  docs/contributions.md
  docs/documentation-links.md
Labels: documentation

#10 Created server.ts with basic express
  src/backend/dist/server.js
  src/backend/dist/server.js.map
  src/backend/package-lock.json
  src/backend/package.json
  src/backend/src/server.ts
  src/backend/tsconfig.json
Labels: enhancement

#21 Fa create sass setup
  src/frontend/concreteindium/package-lock.json
  src/frontend/concreteindium/package.json
  src/frontend/concreteindium/src/App.vue
  src/frontend/concreteindium/src/sass/_functions.scss
  src/frontend/concreteindium/src/sass/_variables.scss
  src/frontend/concreteindium/src/sass/main.scss
  src/frontend/concreteindium/src/views/Home.vue
  src/frontend/concreteindium/vue.config.js
  src/frontend/concreteindium/webpack.config.js
Labels: Design

#20 ✨Added userRoute scaffold in src/routes
  src/backend/dist/routes/userRoute.js
  src/backend/dist/routes/userRoute.js.map
  src/backend/dist/server.js
  src/backend/dist/server.js.map
  src/backend/package.json
  src/backend/src/routes/userRoute.ts
  src/backend/src/server.ts
Labels: enhancement

#24 Created basic authetication scaffold
  src/backend/dist/dBmodule.js
  src/backend/dist/dBmodule.js.map
  src/backend/dist/interfaces/user.js
  src/backend/dist/interfaces/user.js.map
  src/backend/dist/modules/authenticationModule.js
  src/backend/dist/modules/authenticationModule.js.map
  src/backend/dist/routes/userRoute.js
  src/backend/dist/routes/userRoute.js.map
  src/backend/package-lock.json
  src/backend/package.json
  src/backend/src/dBmodule.ts
  src/backend/src/interfaces/user.ts
  src/backend/src/modules/authenticationModule.ts
Labels: enhancement

#25 Added inversify DI container
  src/backend/dist/dBmodule.js
  src/backend/dist/interfaces/userRoute.js
  src/backend/dist/interfaces/userRoute.js.map
  src/backend/dist/inversify.config.js
  src/backend/dist/inversify.config.js.map
  src/backend/dist/routes/userRoute.js
  src/backend/dist/routes/userRoute.js.map
  src/backend/dist/server.js
  src/backend/dist/server.js.map
  src/backend/dist/types.js
  src/backend/dist/types.js.map
  src/backend/package-lock.json
  src/backend/package.json
  src/backend/src/interfaces/userRoute.ts
  src/backend/src/inversify.config.ts
  src/backend/src/routes/userRoute.ts
  src/backend/src/server.ts
  src/backend/src/types.ts
  src/backend/tsconfig.json
Labels: enhancement
